server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
    location ~ \.json$ {
        root /usr/share/nginx/html;
        add_header Access-Control-Allow-Origin *;
    }
# Always end this file with "}" and no additional line break for parsing
}